name: Release [main] to prd

# Controls when the action will run. 
on: push

jobs:
  deploy_prd:  
    name: Deploy to Production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment to deploy to
    environment: 
      name: prd
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context);
            
            // Get the approvals for this run
            const approvals = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            console.log(approvals);

            // Empty check
            if (approvals.data.length == 0){
              core.setFailed(`There are no approvals for this deployment. This is not allowed.`);          
              return; 
            }
             
            // We are only interested in the latest one, which is the first one in the array 
            const latestApproval = approvals.data[0];
            if (latestApproval.user.login == context.actor){
              core.setFailed(`Deployment to the environment is approved by the same person (${context.actor}) who initiated the deployment. This is not allowed.`);            
              return;
            }
